<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" tests="8" skipped="0" failures="0" errors="0" timestamp="2021-04-16T01:55:36" hostname="DESKTOP-3R4DVF7" time="0.598">
  <properties/>
  <testcase name="restNoHandlerFound" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.078"/>
  <testcase name="restGlobalRestPersonControllerExceptionHandlerTakesPrecedenceOverGlobalExceptionHandler" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.072"/>
  <testcase name="restNoException" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.072"/>
  <testcase name="mvcGlobalExceptionHandlerMethodUsingClassArgument" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.073"/>
  <testcase name="restLocalExceptionHandlerMethod" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.072"/>
  <testcase name="restGlobalExceptionHandlerMethod" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.072"/>
  <testcase name="mvcLocalExceptionHandlerMethod" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.088"/>
  <testcase name="mvcGlobalExceptionHandlerMethod" classname="org.springframework.test.web.servlet.samples.standalone.ExceptionHandlerTests" time="0.071"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
